name: "OctoEverywhere"
version: "0.1.0"
slug: "octoeverywhere"
description: "Run OctoEverywhere inside Home Assistant OS"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
image: "octoeverywhere/octoeverywhere:latest"
environment:
  COMPANION_MODE: "bambu"
ports:
  8080/tcp: 8080
options:
  COMPANION_MODE: "bambu"
  PRINTER_IP: ""
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""
schema:
  COMPANION_MODE: str
  PRINTER_IP: str
  ACCESS_CODE: str?
  SERIAL_NUMBER: str?
