name: "OctoEverywhere Bambu"
version: "0.5.0"
slug: "octoeverywhere_bambu"
description: "Home Assistant OS add-on to run OctoEverywhere Bambu Companion for a single printer. Install multiple instances for multiple printers."
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
init: false   # important → don't override the container's entrypoint

# Use the Dockerfile you already made (pulls upstream image)
build:
  context: .
  dockerfile: Dockerfile

options:
  COMPANION_MODE: bambu
  PRINTER_IP: ""
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""

schema:
  COMPANION_MODE: str
  PRINTER_IP: str
  ACCESS_CODE: str
  SERIAL_NUMBER: str
