name: "OctoEverywhere Bambu"
version: "0.1.0"
slug: "octoeverywhere_bambu"
description: "Home Assistant OS add-on to run OctoEverywhere Bambu Companion for up to two printers"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto

# Remove this if you want HAOS to build from your Dockerfile instead
# Make sure you have a multi-arch image if using `image:`
# image: "ghcr.io/octoeverywhere/octoeverywhere-{arch}:latest"

options:
  COMPANION_MODE: "bambu"
  PRINTER1_IP: ""
  PRINTER1_ACCESS_CODE: ""
  PRINTER1_SERIAL_NUMBER: ""
  PRINTER2_IP: ""
  PRINTER2_ACCESS_CODE: ""
  PRINTER2_SERIAL_NUMBER: ""

schema:
  COMPANION_MODE: str
  PRINTER1_IP: str
  PRINTER1_ACCESS_CODE: str
  PRINTER1_SERIAL_NUMBER: str
  PRINTER2_IP: str
  PRINTER2_ACCESS_CODE: str
  PRINTER2_SERIAL_NUMBER: str
