name: OctoEverywhere Bambu Connect
slug: octoeverywhere_bambu
description: "Run OctoEverywhere in Bambu Connect mode inside Home Assistant OS"
version: "1.0.0"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
host_network: true

options:
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""
  PRINTER_IP: ""

schema:
  ACCESS_CODE: string
  SERIAL_NUMBER: string
  PRINTER_IP: string

image: "octoeverywhere/octoeverywhere:latest"
