name: "OctoEverywhere Companion"
version: "2.0.0"
slug: "octoeverywhere"
description: "OctoEverywhere Companion for Bambu printers."
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
init: false
options:
  COMPANION_MODE: "bambu"
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""
  PRINTER_IP: ""
schema:
  COMPANION_MODE: str
  ACCESS_CODE: str
  SERIAL_NUMBER: str
  PRINTER_IP: str
map:
  - config:rw
