name: "OctoEverywhere Bambu"
version: "0.1.0"
slug: "octoeverywhere_bambu"
description: "Home Assistant OS add-on to run OctoEverywhere Bambu Companion for up to two printers"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
image: "octoeverywhere/octoeverywhere:latest"
environment:
  COMPANION_MODE: "bambu"
options:
  PRINTER1_IP: ""
  PRINTER1_ACCESS_CODE: ""
  PRINTER1_SERIAL_NUMBER: ""
  PRINTER2_IP: ""
  PRINTER2_ACCESS_CODE: ""
  PRINTER2_SERIAL_NUMBER: ""
schema:
  PRINTER1_IP: str
  PRINTER1_ACCESS_CODE: str
  PRINTER1_SERIAL_NUMBER: str
  PRINTER2_IP: str
  PRINTER2_ACCESS_CODE: str
  PRINTER2_SERIAL_NUMBER: str
ports: []
