name: "OctoEverywhere Bambu"
version: "0.1.0"
slug: "octoeverywhere_bambu"
description: "Run OctoEverywhere Bambu Companion inside Home Assistant OS"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
image: "octoeverywhere/octoeverywhere:latest"
environment:
  COMPANION_MODE: "bambu"
options:
  PRINTER_IP: ""
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""
schema:
  PRINTER_IP: str
  ACCESS_CODE: str
  SERIAL_NUMBER: str
