name: "OctoEverywhere Bambu"
version: "1.3.0"
slug: "octoeverywhere_bambu"
description: "Home Assistant add-on for OctoEverywhere with Bambu printers"
arch:
  - amd64
  - arm64
startup: services
boot: auto
options:
  COMPANION_MODE: bambu
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""
  PRINTER_IP: ""
schema:
  COMPANION_MODE: str
  ACCESS_CODE: str
  SERIAL_NUMBER: str
  PRINTER_IP: str
