name: OctoEverywhere Bambu Connect
version: "1.0.0"
slug: "octoeverywhere_bambu"
description: "Runs OctoEverywhere in Bambu Connect mode via OctoPrint integration"
arch:
  - amd64
  - aarch64
startup: "services"
boot: "auto"
host_network: true  # if needed to access your printer on LAN
environment:
  ACCESS_CODE: null
  SERIAL_NUMBER: null
  PRINTER_IP: null
schema:
  ACCESS_CODE: string
  SERIAL_NUMBER: string
  PRINTER_IP: string
image: octoeverywhere/octoeverywhere:latest
