name: "OctoEverywhere Bambu"
version: "1.1.0"
slug: "octoeverywhere_bambu"
description: "Run OctoEverywhere Bambu Companion in Home Assistant"
url: "https://github.com/Zeunas/octoeverywhere-ha-addon"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
options:
  COMPANION_MODE: bambu
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""
  PRINTER_IP: ""
schema:
  COMPANION_MODE: str
  ACCESS_CODE: str
  SERIAL_NUMBER: str
  PRINTER_IP: str
