name: "OctoEverywhere Bambu"
version: "0.29.0"
slug: "octoeverywhere_bambu"
description: "Home Assistant OS add-on to run OctoEverywhere Bambu Companion for a single printer."
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
init: false

options:
  COMPANION_MODE: "bambu"
  PRINTER_IP: ""
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""

schema:
  COMPANION_MODE: string
  PRINTER_IP: string
  ACCESS_CODE: string
  SERIAL_NUMBER: string

map:
  - config:rw
  - data:rw
