name: "OctoEverywhere Bambu"
version: "0.13.0"
slug: "octoeverywhere_bambu"
description: "Home Assistant OS add-on to run OctoEverywhere Bambu Companion for a single printer. Install multiple instances for multiple printers."
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
init: false

# Build from our Dockerfile, not pull image
build:
  context: .
  dockerfile: Dockerfile

options:
  PRINTER_IP: ""
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""

schema:
  PRINTER_IP: str
  ACCESS_CODE: str
  SERIAL_NUMBER: str

map:
  - config:rw
  - data:rw
