name: "OctoEverywhere Bambu"
version: "0.29.0"
slug: "octoeverywhere_bambu"
description: "Home Assistant OS add-on to run OctoEverywhere Bambu Companion for a single printer."
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
init: false
#host_network: true

options:
  ACCESS_CODE: ""
  SERIAL_NUMBER: ""
  PRINTER_IP: ""

schema:
  ACCESS_CODE: str
  SERIAL_NUMBER: str
  PRINTER_IP: str

image: "octoeverywhere/octoeverywhere:latest"
