#!/usr/bin/with-contenv bashio
set -e

export COMPANION_MODE="${COMPANION_MODE}"
export PRINTER1_IP="${PRINTER1_IP}"
export PRINTER1_ACCESS_CODE="${PRINTER1_ACCESS_CODE}"
export PRINTER1_SERIAL_NUMBER="${PRINTER1_SERIAL_NUMBER}"
export PRINTER2_IP="${PRINTER2_IP}"
export PRINTER2_ACCESS_CODE="${PRINTER2_ACCESS_CODE}"
export PRINTER2_SERIAL_NUMBER="${PRINTER2_SERIAL_NUMBER}"

exec /path/to/octoeverywhere-binary
